### PR TITLE
Fix #116: updated .dat file in catena4612_simple for the repo Adafruit_Sensor

### LINKED ISSUE #116: catena4612_simple needs "Adafruit_Unified_Sensor"
The Adafruit_BME280_Library seems to require the Adafruit Unified Sensor library. 

Installing it manually takes care of the error.

### PR DESCRIPTION
**Pull request by dhineshkumarmcci**
Updated the `git-repos.dat` for sketch `catena4612_simple` with the repo `Adafruit_Sensor`. Tested in parallel, able to build without any errors.
Reference to issue #116

### CODE REVIEW

**Comment by terrillmoore** [comment]
Thanks, I'll merge after the CI tests complete. Did you check the other `git-repos.dat` files to see if they have similar problems?

**Comment by dhineshkumarmcci** [comment]
Yes Terry, able to see below repos missing the Adafruit_Sensor library:

- [catena4551_test01](https://github.com/mcci-catena/Catena-Sketches/tree/master/catena4551_test01)
- [catena4551_test02](https://github.com/mcci-catena/Catena-Sketches/tree/master/catena4551_test02)
- [catena461x_test01](https://github.com/mcci-catena/Catena-Sketches/tree/master/catena461x_test01)
- examples in [MCCI-Catena-PMS7003](https://github.com/mcci-catena/MCCI-Catena-PMS7003/tree/master/examples)

Also examples in [MCCI-Catena-PMS7003](https://github.com/mcci-catena/MCCI-Catena-PMS7003/tree/master/examples) require with change of `Adafruit_FRAM_I2C` with `MCCI_FRAM_I2C`.

**Comment by terrillmoore** [comment]
> 
> 
> Yes Terry, able to see below repos missing the Adafruit_Sensor library:
> 
>     * [catena4551_test01](https://github.com/mcci-catena/Catena-Sketches/tree/master/catena4551_test01)
> 
>     * [catena4551_test02](https://github.com/mcci-catena/Catena-Sketches/tree/master/catena4551_test02)
> 
>     * [catena461x_test01](https://github.com/mcci-catena/Catena-Sketches/tree/master/catena461x_test01)
> 
>     * examples in [MCCI-Catena-PMS7003](https://github.com/mcci-catena/MCCI-Catena-PMS7003/tree/master/examples)
> 
> 
> Also examples in [MCCI-Catena-PMS7003](https://github.com/mcci-catena/MCCI-Catena-PMS7003/tree/master/examples) require with change of `Adafruit_FRAM_I2C` with `MCCI_FRAM_I2C`.

Thanks. Can you please push updates for these, too?

**Comment by dhineshkumarmcci** [comment]
Updated the '.dat' files and submitted Pull-request #119

**Pull request merged**
